"""Repository port interfaces.

Repositories hide persistence and translate ORM rows to domain entities. Use cases
depend only on these Protocols; infrastructure supplies concrete SQLAlchemy impls.
"""

from __future__ import annotations

import uuid
from datetime import date
from typing import Protocol, Sequence

from app.domain.entities import (
    ChatMessage,
    DailyCheckIn,
    DailyEnvironmentTip,
    HealthProfile,
    PhoneOtp,
    User,
    WebAuthnCredential,
    WeeklyPlan,
)
from app.domain.value_objects import ChatRole, Email, PhoneE164


class UserRepository(Protocol):
    def get_by_id(self, user_id: uuid.UUID) -> User | None: ...
    def get_by_email(self, email: Email) -> User | None: ...
    def get_by_phone(self, phone: PhoneE164) -> User | None: ...
    def get_by_google_sub(self, google_sub: str) -> User | None: ...
    def add(self, user: User) -> User: ...
    def update(self, user: User) -> User: ...
    def list_ids_with_profile(self) -> list[uuid.UUID]: ...


class PhoneOtpRepository(Protocol):
    def add(self, otp: PhoneOtp) -> PhoneOtp: ...
    def get_latest_active_for_phone(self, phone: PhoneE164) -> PhoneOtp | None: ...
    def update(self, otp: PhoneOtp) -> PhoneOtp: ...


class WebAuthnCredentialRepository(Protocol):
    def add(self, credential: WebAuthnCredential) -> WebAuthnCredential: ...
    def list_for_user(self, user_id: uuid.UUID) -> list[WebAuthnCredential]: ...
    def get_by_credential_id(self, credential_id: bytes) -> WebAuthnCredential | None: ...
    def update(self, credential: WebAuthnCredential) -> WebAuthnCredential: ...
    def delete(self, credential_id: uuid.UUID) -> None: ...


class HealthProfileRepository(Protocol):
    def get_by_user_id(self, user_id: uuid.UUID) -> HealthProfile | None: ...
    def upsert(self, profile: HealthProfile) -> HealthProfile: ...


class ChatRepository(Protocol):
    def add(self, message: ChatMessage) -> ChatMessage: ...
    def list_recent_user_messages(
        self, user_id: uuid.UUID, days: int = 7, limit: int = 80
    ) -> list[ChatMessage]: ...
    def list_semantic_user_messages(
        self,
        user_id: uuid.UUID,
        query_embedding: list[float],
        days: int = 7,
        limit: int = 5,
    ) -> list[ChatMessage]: ...


class CheckInRepository(Protocol):
    def get_for_date(self, user_id: uuid.UUID, d: date) -> DailyCheckIn | None: ...
    def list_week(
        self, user_id: uuid.UUID, start: date, end: date
    ) -> list[DailyCheckIn]: ...
    def upsert(self, check_in: DailyCheckIn) -> DailyCheckIn: ...


class WeeklyPlanRepository(Protocol):
    def get_for_week(
        self, user_id: uuid.UUID, week_start: date
    ) -> WeeklyPlan | None: ...
    def upsert(self, plan: WeeklyPlan) -> WeeklyPlan: ...
    def save_envelope(self, plan: WeeklyPlan) -> WeeklyPlan:
        """Save mutations inside `plan.tasks` (JSONB must be flagged as modified)."""
        ...


class EnvironmentTipRepository(Protocol):
    def get_for_date(
        self, user_id: uuid.UUID, tip_date: date
    ) -> DailyEnvironmentTip | None: ...
    def add(self, tip: DailyEnvironmentTip) -> DailyEnvironmentTip: ...


class AuditLogRepository(Protocol):
    def record(self, actor: str, action: str) -> None: ...
